---
deployment:
 tasks:
 - export DEPLOYPATH=/home/tnhlabsc/svboost.com/
 - /bin/cp -R authentication $DEPLOYPATH
 - /bin/cp -R blog $DEPLOYPATH
 - /bin/cp -R config $DEPLOYPATH
 - /bin/cp -R db $DEPLOYPATH
 - /bin/cp -R main $DEPLOYPATH
 - /bin/cp -R payment $DEPLOYPATH
 - /bin/cp -R report $DEPLOYPATH
 - /bin/cp -R static $DEPLOYPATH
 - /bin/cp -R templates $DEPLOYPATH
 - /bin/cp -R tmp $DEPLOYPATH
 - /bin/cp -R Wiki $DEPLOYPATH
 - /bin/cp .env $DEPLOYPATH
 - /bin/cp .htaccess $DEPLOYPATH
 - /bin/cp app.py $DEPLOYPATH
 - /bin/cp deploy.sh $DEPLOYPATH
 - /bin/cp favicon.ico $DEPLOYPATH
 - /bin/cp get-pip.py $DEPLOYPATH
 - /bin/cp install.sh $DEPLOYPATH
 - /bin/cp passenger_wsgi.py $DEPLOYPATH
 - /bin/cp Pipfile $DEPLOYPATH
 - /bin/cp Pipfile.lock $DEPLOYPATH
 - /bin/cp Procfile $DEPLOYPATH
 - /bin/cp requirements.txt $DEPLOYPATH
 - /bin/cp robots.txt $DEPLOYPATH
 - /bin/cp server.sh $DEPLOYPATH
 - /bin/cp stopwords.txt $DEPLOYPATH
 - /bin/cp tmp-main.zip $DEPLOYPATH