"""adding showTour

Revision ID: 033597b2523c
Revises: 30655709b10a
Create Date: 2021-08-18 04:25:57.769602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033597b2523c'
down_revision = '30655709b10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resource_usage', sa.Column('showTour', sa.Boolean(), unique=False, nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resource_usage', 'showTour')
    # ### end Alembic commands ###
