"""empty message

Revision ID: 2718620a3ad8
Revises: d952a353b1a0
Create Date: 2023-02-19 07:56:16.256747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2718620a3ad8'
down_revision = 'd952a353b1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
