"""empty message

Revision ID: 2fcf418cfc26
Revises: dd9253b96d23
Create Date: 2023-02-21 06:38:47.356725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcf418cfc26'
down_revision = 'dd9253b96d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.String(length=150), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('product_id')
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###
