"""create_status_field_on_user

Revision ID: 30655709b10a
Revises:
Create Date: 2021-06-30 22:15:18.256538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30655709b10a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
