"""empty message

Revision ID: 4d4e7e4585d8
Revises: ca8527516a8f
Create Date: 2023-02-21 08:12:14.441308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4e7e4585d8'
down_revision = 'ca8527516a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.String(length=150), nullable=True))
        batch_op.drop_column('product_stripe')
        batch_op.drop_column('price_stripe')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_stripe', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('product_stripe', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('product_id')
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###
