"""empty message

Revision ID: ca8527516a8f
Revises: 2fcf418cfc26
Create Date: 2023-02-21 07:16:04.496123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8527516a8f'
down_revision = '2fcf418cfc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_stripe', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('product_stripe', sa.String(length=150), nullable=True))
        batch_op.drop_column('product_id')
        batch_op.drop_column('price_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_id', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('product_stripe')
        batch_op.drop_column('price_stripe')

    # ### end Alembic commands ###
